### ISSUE TITLE
Is there a easy way to add a datatable-card with pagination??

### ISSUE THREAD

**Issue by oscar-dario-pabon** [David-Mulder/paper-datatable#116]
Hi!,

Can anyone explain me how to implements a datatable-card with pagination??

Thanks.

**Comment by RoXuS** [comment]
Hi @senneko, you want pagination with a backend ?

This project is not longer maintained, you can use https://github.com/RoXuS/paper-datatable-api instead of this.

You have an exemple with pagination and an iron-ajax here : https://github.com/RoXuS/paper-datatable-api/blob/master/demo/advanced-demo.html

**Comment by oscar-dario-pabon** [comment]
Thanks a lot!!!
