### ISSUE TITLE
Scroll overflow with fixed header

### ISSUE THREAD

**Issue by xmakro** [David-Mulder/paper-datatable#29]
The rows should be scrollable by overflow and the table head should not be scrolled

**Comment by David-Mulder** [comment]
@makrolabs As far as I know this is is a generic feature request and not based on the material design spec. Am I correct?

**Comment by David-Mulder** [comment]
Though I have to say I am quite averse to implementing this. Initially I had to make a choice between an infinite scrolling list or pagination. Due to the way I support `<template>` tags both are incredibly hard to pull off to be honest and supporting both is not something I care to do (at least in the foreseeable future). As the MD spec goes with pagination rather than infinite scrolling lists I decided to follow this decision and a floating header sounds like something that belongs in an infinite scrolling list datatable. Which of course doesn't mean I am not open to a discussion xD Who knows, maybe I am forgetting stuff.
