### ISSUE TITLE
How to set length of dataSource after ajax request

### ISSUE THREAD

**Issue by kersten** [David-Mulder/paper-datatable#47]
Hi,

I can't find out how to set the length of a dataSource after I made an ajax request. Could you give me a hint or is this not implemented yet?

I tried

```
length: function () {
    return new Promise( function ( resolve, reject ) {
        resolve(500);
    } );
}

self.dataSource.length = 500;
self.dataSource.set( 'length', 500 );
self.dataSource.set( 'numberOfItems', 500 );
self.$.datatable._setNumberOfItems( 500 );
```

Thanks for your help

Greetings Kersten

**Comment by David-Mulder** [comment]
Like always you use `element.set('dataSource.length')` to set a sub property, otherwise the element won't be notified and that's what I am using in my own production implementation (setting it first to 0 and then updating it). Regardless though, I would expect `self.$.datatable._setNumberOfItems( 500 );` to work as well though... :/

**Comment by David-Mulder** [comment]
Ah, maybe your `$.datatable` is actually the `<paper-datatable>` instead of the `<paper-datatable-card>`. That would at least explain that part.

**Comment by kersten** [comment]
Thank you. missed the initial `length: 0`. Now its work :) Great!
