### ISSUE TITLE
Feature: jump to page

### ISSUE THREAD

**Issue by NamTThai** [David-Mulder/paper-datatable#57]
For `paper-datatable-card`, I think it would be great to have a feature to jump to a certain page, in addition to next/previous. Awesome for large data table

**Comment by David-Mulder** [comment]
@NamTThai Well... why is that awesome? Like honestly, according to the MD spec you shouldn't even add 'first' and 'last' buttons. They do not explain their reasoning, but after I started thinking it through myself it turned out to be quite logical: it never makes sense to go to the last page, because that's what sorting is for (if you want the oldest item you should simply sort the `date_created` column that way). So why did I add those buttons none the less? Because going back to the first page actually makes a lot of sense and because sorting once and then going to the last page instead of simply sorting twice is maybe not the most logical thing to do, but at least it's a valid use case.

Now, to get to the option to jump to a certain page. What kind of user would ever want to jump to a certain page? Why would the end user ever want to remember the specific page an item is on and then go to it? I mean, any case where I can imagine an end user being forced to do that sounds like a symptom of **very** bad UX design. For example if no sorting and no search would be implemented. 

Do please present your use case however, and just a tip, if the above doesn't convince you and your  arguments do not end up convincing me: You can always add a 'go to page' button in your toolbar which would prompt a simple input dialog where you can enter a page number.

**Comment by NamTThai** [comment]
+1 that makes sense I forgot that searching and filtering are coming
