### ISSUE TITLE
Don't work in IE9+

### ISSUE THREAD

**Issue by tookit** [David-Mulder/paper-datatable#65]

**Comment by David-Mulder** [comment]
Half true, Edge is considered the newest version of IE and I only try to support the most recent version of modern browsers. Either way, your issue did motivate me to write a bit more on the topic, so: http://david-mulder.github.io/paper-datatable/components/paper-datatable/docs/docs.html?browser-support

**Comment by tookit** [comment]
Yes, it work fine in Edge.
Anyway, it is the best polymer data table I ever found. But if it can support IE9,IE10,IE11, it will be teriffic. I'm trying to fix the issue, but it give a strange "Syntax error" and I cannot even locate it.

**Comment by Protoss78** [comment]
My quick assumption here:
The Syntax error is caused by the usage of ECMAScript 6 arrow functions. I ran into the same problem in Chrome 43, which I ran into when I tested paper-datatable in a hybrid Android app. This error could be fixed by a pull request that was already submitted but is waiting for a merge.

**Comment by David-Mulder** [comment]
@Protoss78 @tookit Arrow functions do not solve the issue in IE, I checked. Initially I wasn't using arrow functions specifically because of IE and Safari, but afterwards I found out it wasn't working either way in those browsers and I simply gave up on them as outlined in the linked document above. If someone would be able to fix IE11 (without specific changes for IE9 or IE10) I might consider it, but if the cost is too great as far as code goes I have to say that I am not invested enough to support it. What it boils down to is the following: I do not think it's correct to build a component for a specific browser like in the IE6 days or later the Chrome days, however at the same time I do think developers have the responsibility to inform users when they use crappy browsers. And yes, as I write in the link above:

> Some stats to back this up: caniuse.com is a site which covers technology adoption in browsers. Considering JS API's Safari only supports 50% (like IE) of the covered API's compared to the next worst browser (Edge) which covers 71%. And just for comparisons sake the most recent versions of Firefox cover 89% and Chrome 82%. That's simply a HUGE difference.

And writing everything with the lowest common denominator in mind takes twice as much time which is time I don't have (it already took a ridiculous amount of time to develop this). Does that sound so odd?

**Comment by David-Mulder** [comment]
I feel like my choice is fairly harsh, so here are a few more thoughts on the topic:

---

And there is one other thing that plays a role: The dev tools in IE (_and_ Edge) suck BIG TIME. And dev tools for Safari are realistically non-existent as Apple has decided not to release virtual testing machines like Microsoft has, nor make it's browser cross platform. Microsoft cares about developers supporting their browsers, as proven by a literal quote like this:

> No PC? No problem. Our tools and virtual machines are free and cross-platform, so you can test your site today on your favorite device—even a Mac.

And Apple does not as proven by the fact they even pulled Safari from Windows. I mean, making Edge work was quite a pain as well (till an update in Edge fixed a couple of bugs and nearly all suddenly magically worked) but for the reason above I always intended from the start to support Microsoft's latest offering.

**Comment by tookit** [comment]
Thanks.
In developer's view, I could not agree more with you.
I'm looking forward to more new features.such as frozen column.

**Comment by David-Mulder** [comment]
@tookit Not sure what you mean with 'frozen column', but feel free to open an issue for that ;-)
